# Generated by Django 2.1.8 on 2019-04-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', to='manytomany.Doctor'),
        ),
    ]
